[build]
target = "x86_64-unknown-none"


[unstable]
profile-rustflags = true
build-std = ["core", "compiler_builtins"] 
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(target_os = "none")'] 
runner = "bootimage runner"

[profile.release]
panic = "abort"
rustflags = ["-C", "link-arg=-Tlinker.ld"]
